services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: cucchiaio
      POSTGRES_USER: cucchiaio
      POSTGRES_PASSWORD: cucchiaio
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

  app:
    build:
      context: ./cucchiaio
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cucchiaio
      DB_USER: cucchiaio
      DB_PASSWORD: cucchiaio
      JWT_SECRET: zm127rg6rKJuHuWYQVrJs2IBgbyDzm9b6LF0yQ004bY=
    depends_on:
      - db

volumes:
  db-data: