package nl.wouterdoeland.cucchiaio.repository;

import nl.wouterdoeland.cucchiaio.domain.DietaryOption;
import nl.wouterdoeland.cucchiaio.domain.Recipe;
import nl.wouterdoeland.cucchiaio.domain.RecipeIngredient;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

class RecipeRepositoryIT extends AbstractPostgresIT {
    // skeleton generated by Claude

    // two test users
    private static final String ALICE = "alice-sub";
    private static final String BOB = "bob-sub";

    @Autowired
    private RecipeRepository repository;

    // four test recipes
    private Recipe ovenSalmon;              // alice: oven instructions, has salmon
    private Recipe vegetarianGnocchi;       // alice: vegetarian, contains potato gnocchi
    private Recipe lasagna;                 // alice: oven lasagna, contains meat
    private Recipe bobsRecipe;              // bob: someone else's, for ownership tests

    /**
     * Seed database with entries
     */
    @BeforeEach
    void seed() {
        repository.deleteAll();

        ovenSalmon = new Recipe(ALICE,
                "Baked Salmon",
                2,
                "Preheat the oven to 200 degrees C. Bake the salmon in the oven for twenty minutes.",
                List.of());
        ovenSalmon.addIngredient(new RecipeIngredient("Salmon", BigDecimal.valueOf(400), "gram"));
        ovenSalmon.addIngredient(new RecipeIngredient("Lemon", BigDecimal.valueOf(1), null));

        vegetarianGnocchi = new Recipe(ALICE,
                "Vegetarian Gnocchi",
                4,
                "Boil the potatoes. Dice and kneed into dough. Boil again. Strain and add cheese to taste.",
                List.of(DietaryOption.VEGETARIAN));
        vegetarianGnocchi.addIngredient(new RecipeIngredient("Potatoes", new BigDecimal("0.5"), "kg"));
        vegetarianGnocchi.addIngredient(new RecipeIngredient("Parmigiano Reggiano", null, null));

        lasagna = new Recipe(ALICE,
                "Lasagna",
                6,
                "Boil the pasta. Make the sauce. Add together. Put into oven.",
                List.of());
        lasagna.addIngredient(new RecipeIngredient("Pasta", BigDecimal.valueOf(500), "gram"));
        lasagna.addIngredient(new RecipeIngredient("Minced Meat", BigDecimal.valueOf(500), "gram"));
        lasagna.addIngredient(new RecipeIngredient("Onion", BigDecimal.valueOf(1), null));

        bobsRecipe = new Recipe(BOB,
                "Bob's Secret Minestrone",
                5,
                "Boil the vegetables in broth.",
                List.of(DietaryOption.VEGETARIAN));
        bobsRecipe.addIngredient(new RecipeIngredient("Veggies", BigDecimal.valueOf(2), "kg"));
        bobsRecipe.addIngredient(new RecipeIngredient("Potatoes", BigDecimal.valueOf(5), null));

        repository.saveAll(List.of(ovenSalmon, vegetarianGnocchi, lasagna, bobsRecipe));
    }

    /**
     * Basic CRUD testing
     */
    @Nested
    @DisplayName("CRUD")
    class Crud {
        @Test
        void saveAndFindById_roundTrips() {
            Recipe saved = repository.save(new Recipe(ALICE,
                    "Pancakes",
                    3,
                    "Whisk and fry.",
                    List.of()));

            Optional<Recipe> found = repository.findById(saved.getId());

            assertThat(found).isPresent();
            assertThat(found.get().getTitle()).isEqualTo("Pancakes");
            assertThat(found.get().getServingSize()).isEqualTo(3);
        }

        @Test
        void deletingRecipe_cascadesToIngredients() {
            Long id = ovenSalmon.getId();
            assertThat(repository.findById(id)).isPresent();

            repository.deleteById(id);

            assertThat(repository.findById(id)).isEmpty();
            // No orphaned ingredient rows: a fresh search returns nothing for it.
            assertThat(repository.findAllByOwnerId(ALICE))
                    .extracting(Recipe::getId)
                    .doesNotContain(id);
        }

        @Test
        void count_reflectsSeededRows() {
            assertThat(repository.count()).isEqualTo(4);
        }
    }

    /**
     * Check if ownership of recipes works properly
     */
    @Nested
    @DisplayName("Ownership scoping")
    class Ownership {

        @Test
        void findByIdAndOwnerId_returnsOwnRecipe() {
            Optional<Recipe> found =
                    repository.findByIdAndOwnerId(ovenSalmon.getId(), ALICE);
            assertThat(found).isPresent();
        }

        @Test
        void findByIdAndOwnerId_returnsEmptyForOtherUsersRecipe() {
            // Bob's recipe exists, but Alice must not be able to fetch it.
            // Empty (not an exception) so the controller answers 404, not 403,
            // and never reveals that the recipe exists.
            Optional<Recipe> found =
                    repository.findByIdAndOwnerId(bobsRecipe.getId(), ALICE);
            assertThat(found).isEmpty();
        }

        @Test
        void findAllByOwnerId_returnsOnlyThatOwnersRecipes() {
            assertThat(repository.findAllByOwnerId(ALICE))
                    .extracting(Recipe::getTitle)
                    .containsExactlyInAnyOrder("Baked Salmon", "Lasagna", "Vegetarian Gnocchi");
            assertThat(repository.findAllByOwnerId(BOB))
                    .extracting(Recipe::getTitle)
                    .containsExactly("Bob's Secret Minestrone");
        }
    }

    /**
     * Search testing
     */
    @Nested
    @DisplayName("Search")
    class Search {

        @Test
        void noFilters_returnsAllOwnRecipes() {
            List<Recipe> results = repository.search(ALICE, null, null, null, null, null, null);
            assertThat(results)
                    .extracting(Recipe::getTitle)
                    .containsExactlyInAnyOrder("Baked Salmon", "Vegetarian Gnocchi", "Lasagna");
        }

        @Test
        void nullOwner_searchesAcrossAllOwners() {
            List<Recipe> results = repository.search(null, null, null, null, null, null, null);
            assertThat(results).hasSize(4); // includes Bob's
        }

        @Test
        void fullTextMatchesStemmedWordInInstructions() {
            // "oven" appears literally; full-text also stems, so "bake" matches "Bake".
            List<Recipe> oven = repository.search(null, "oven", null, null, null, null, null);
            assertThat(oven).extracting(Recipe::getTitle).containsExactlyInAnyOrder("Baked Salmon", "Lasagna");
        }

        @Test
        void servingsRange_filtersInclusively() {
            // lower bound only: >= 6
            assertThat(repository.search(null, null, 6, null, null, null, null))
                    .extracting(Recipe::getTitle).containsExactly("Lasagna");
            // upper bound only: <= 2
            assertThat(repository.search(null, null, null, 2, null, null, null))
                    .extracting(Recipe::getTitle).containsExactly("Baked Salmon");
        }

        @Test
        void dietary_requiresTag() {
            // both alice recipes are gluten-free
            assertThat(repository.search(ALICE, null, null, null,
                    new String[]{DietaryOption.VEGETARIAN.name()}, null, null))
                    .extracting(Recipe::getTitle).containsExactly("Vegetarian Gnocchi");
        }

        @Test
        void includedIngredients_requiresAll() {
            assertThat(repository.search(ALICE, null, null, null, null,
                    new String[]{"potatoes", "parmigiano reggiano"}, null))
                    .extracting(Recipe::getTitle).containsExactly("Vegetarian Gnocchi");
            assertThat(repository.search(ALICE, null, null, null, null,
                    new String[]{"tofu", "salmon"}, null))
                    .isEmpty();
        }

        @Test
        void excludedIngredients_removesMatches() {
            assertThat(repository.search(ALICE, null, null, null, null, null,
                    new String[]{"potatoes", "onion"}))
                    .extracting(Recipe::getTitle).containsExactly("Baked Salmon");
        }

        @Test
        void combinedFilters_fromTheAssessment() {
            // recipes without salmon as an ingredient that have oven in the instructions
            assertThat(repository.search(null, "oven", null, null,
                    null, null, new String[]{"salmon"}))
                    .extracting(Recipe::getTitle).containsExactly("Lasagna");

            // recipes that can serve 4 persons and have "potatoes" as an ingredient
            assertThat(repository.search(null, null, 4, null,
                    null, new String[]{"potatoes"}, null))
                    .extracting(Recipe::getTitle).containsExactlyInAnyOrder("Vegetarian Gnocchi", "Bob's Secret Minestrone");
        }

        @Test
        void searchRespectsOwnerScope() {
            // Bob's stew is vegan, but Alice's scoped search must never see it.
            assertThat(repository.search(ALICE, null, null, null,
                    new String[]{DietaryOption.VEGETARIAN.name()}, new String[]{"veggies"}, null))
                    .isEmpty();
        }
    }
}